services:
  - type: web
    name: book-recommendation
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        from: secret:OPENAI_API_KEY
